services:
  vendor-machine:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - .:/var/www:cached
    networks:
      - vendor-machine-network
    command:
      tail -f /dev/null


networks:
  vendor-machine-network:
    driver: bridge